- hosts: websphere
  gather_facts: min
  tasks:
    - name: Message to display the date and time
      debug:
        var: ansible.date_time

    - name: Install apache
      package:
        name: httpd
        status: present

